### ISSUE TITLE
Create javafx front end (Epic)

### ISSUE THREAD

**Issue by codyferguson** [codyferguson/BroadswordBadassI#4]
- [x] create basic structure
- [x] Create Welcome screen
- [x] Create Main screen
- [ ] Create character information panel
- [x] Create combat text box
- [x] Create action buttons below text box

**Comment by codyferguson** [comment]
Need to fix final format then this is complete
